redirect uri from route
rootinc/laravel-azure-middleware pull request #53
Opened 2021-09-25 02:19 UTC by jimmypuckett

This will Fix #37 

I am using a named route `azure.callback` when defining the route, so there is really nothing extra to configure.

2021-09-25 02:35 UTC, jimmypuckett commented
@danieltjewett I got to thinking about this change, & it would be breaking for someone that already had the package installed without the named route, so I am not sure if you would want to put logic testing for the named route or tag a minor version change?

2021-09-27 13:32 UTC, danieltjewett requested changes
@jimmypuckett Thanks for contributing!  Now I understand a bit more what the original issue was asking for.  We've always supplied the callback route in the Azure portal.  However, I can see this use case.

> I got to thinking about this change, & it would be breaking for someone that already had the package installed without the named route

Yes, I would agree.  And, for those like us who are using the callback from the portal as oppose this convention would also have potential issues.  I would assume the callback param passed would take precedence over what is in the portal.

My suggestion would be check to see if the named route exists.  If it does, pass the `redirect_uri` key in.

Obviously this changes a bit of the readme and might make the code a bit gross.  I'll note some ways to remedy this in the code.

2021-09-27 13:32 UTC, danieltjewett commented on src/Azure.php
> +                    'redirect_uri' => route('azure.callback'),
Make this an optional parameter.  Perhaps move `form_param` into its own hash above the try catch.  Then, check to see if the `route('azure.callback`)` exists.  If it does, add the key.

2021-09-27 13:32 UTC, danieltjewett commented on src/Azure.php
> +        return $this->baseUrl . config('azure.tenant_id') . $this->route2 . "authorize?response_type=code&client_id=" . config('azure.client.id') . "&domain_hint=" . urlencode(config('azure.domain_hi
Let's create a string called `url` and then set it to what it was originally.  Then, check to see if the `azure.callback` route exists and if it does, append as suggested.

2021-09-27 13:32 UTC, danieltjewett commented on README.md
> +Route::get('/login/azure', '\RootInc\LaravelAzureMiddleware\Azure@azure')
Let's add a step (3.a, 3.b?, or just a new int) that mentioned the possibility of naming routes.  If we name the route, we don't have to configure the callback on the portal.  If we don't, we need to make sure we add the URL in the portal.

2021-09-27 13:32 UTC, danieltjewett commented on README.md
> +Route::get('/login/azurecallback', '\App\Http\Middleware\AppAzure@azurecallback')
I would just add a note saying `if we are using named routes, be sure to add the named routes here appropriately.`

2021-09-27 13:32 UTC, danieltjewett commented on README.md
> +        return $this->baseUrl . config('azure.tenant_id') . $this->route2 . "authorize?response_type=code&client_id=" . config('azure.client.id') . "&domain_hint=" . urlencode(config('azure.domain_hi
Make sure to update to new code to account for the callback.

2021-09-27 13:38 UTC, jimmypuckett commented
One note about this...

> Yes, I would agree. And, for those like us who are using the callback from the portal as oppose this convention would also have potential issues. I would assume the callback param passed would take precedence over what is in the portal.

You still have to set up the callback in the portal, and the callback is passed in will not work unless it is in the portal first.  This just allows you to have a single app configured with multiple callbacks for different environments  (local, staging, production, etc).

2021-09-27 13:41 UTC, jimmypuckett commented
@danieltjewett I will try to look over these suggestions/changes later tonight.  It is going to be a very busy week, so I will see what I can do.  Thanks for the feedback.

2021-09-27 13:42 UTC, danieltjewett commented
@jimmypuckett Not a problem!  I understand the busyness (which is why I took a couple days for me to review).

2021-09-27 13:45 UTC, danieltjewett commented
@jimmypuckett Missed the first comment.  Love the idea of having multiple environments.  We've been creating separate apps for different environments.  This is way better :D

2021-10-09 10:10 UTC, jimmypuckett commented on src/Azure.php
> +                    'redirect_uri' => route('azure.callback'),
OK, I have just done this in 5b81293ef77659063c32e8f3780eb3b821a3d17e

2021-10-09 10:10 UTC, jimmypuckett commented on src/Azure.php
> +        return $this->baseUrl . config('azure.tenant_id') . $this->route2 . "authorize?response_type=code&client_id=" . config('azure.client.id') . "&domain_hint=" . urlencode(config('azure.domain_hi
Done in 5b81293ef77659063c32e8f3780eb3b821a3d17e

2021-10-09 10:11 UTC, jimmypuckett commented on README.md
> +Route::get('/login/azure', '\RootInc\LaravelAzureMiddleware\Azure@azure')
Done in 5bfdd2b44e382d77066b7518d9804d0d3d8cef30

2021-10-09 10:11 UTC, jimmypuckett commented on README.md
> +Route::get('/login/azurecallback', '\App\Http\Middleware\AppAzure@azurecallback')
Done in 5bfdd2b44e382d77066b7518d9804d0d3d8cef30

2021-10-09 10:11 UTC, jimmypuckett commented on README.md
> +        return $this->baseUrl . config('azure.tenant_id') . $this->route2 . "authorize?response_type=code&client_id=" . config('azure.client.id') . "&domain_hint=" . urlencode(config('azure.domain_hi
Done in 5bfdd2b44e382d77066b7518d9804d0d3d8cef30

2021-10-09 10:12 UTC, jimmypuckett commented
@danieltjewett I finally got a break to make the tweaks that you suggested.  Please let me know if there is anything else.

Thanks.

2021-10-27 01:50 UTC, jimmypuckett commented
@danieltjewett I know that I got tied up & took a bit to implement your suggestions, but do you think that you could review/merge this.  We have been working on a project that is a few weeks from being live, so this would be super nice to have for the UAT & prod environments without having to set up additional applications in the portal.

Thanks!

2021-10-29 17:34 UTC, danieltjewett commented
@jimmypuckett sorry about that.  I am actually no longer a part of the rootinc org, and didn't get this notification via normal email.  I just happened to see this in my github notifications.  @jaredrhodes could you review this?

2021-10-29 17:38 UTC, jimmypuckett commented
@danieltjewett thanks for the update.

@jaredrhodes if this is not something that you guys have the time to keep alive, I would be happy to take over the support & maintenance of it along with all of our other Laravel packages.  Just let me know.  Thanks.

2021-11-01 15:34 UTC, jaredrhodes commented
Hi @jimmypuckett, `#thanksdan` @danieltjewett. Since I'm fresh on this, correct me wrong...

**Summary**: Handle multiple environments within a single App Registration.
- In a single Azure App Registration, one can register multiple "Redirect URIs" like `"https://myapp.test/auth"`, and `"https://staging.myapp.com/auth"` to handle multiple environments.
-  If no `'azure.callback'` named route exists carry on as previous using the only or last "Redirect URI" registered in Azure App Registration.
- If a route is named `'azure.callback'` will be turned into a a URL and sent off in the auth request. If a match is found in Azure App Registration's "Redirect URIs", a valid login will redirect to that URL.

This looks to be backward compatible where if someone does not register a route with `->name('azure.callback');` we carry on as usual and if they do register a route with `->name('azure.callback');` we use that value?

2021-11-01 15:44 UTC, jimmypuckett commented
Yes, that is the key concept of the MR, and yes, it should be backward compatible.

2021-11-02 13:05 UTC, danieltjewett commented
@jaredrhodes That is correct. :shipit:

2021-11-02 20:44 UTC, jaredrhodes approved these changes

2021-11-02 20:45 UTC, merged